### ISSUE TITLE
SPA Integration for docker compose

### ISSUE THREAD

**Issue by azdanov** [dantheman213/java-spring-mvc-rest-bootstrapped-app#1]
Any tips on how one might integrate a Vue.js/React single-page application? I'm new to the Spring/Gradle and would be grateful for more insight.

Here are some of my thoughts.

For development:

1. My current process is to create a `frontend` directory in the project root while proxying requests from the frontend client to the backend api.

2. Add a `Dockerfile` inside with (this is for Vue.js): 
	```dockerfile
	FROM node:lts-alpine
	
	WORKDIR /app
	COPY package*.json ./
	RUN npm install
	COPY . .
	
	CMD [ "npm", "run", "serve" ]
	```
3. Add a new section to `services` in `docker-compose.yml`:
	```yml
	  frontend:
	    build: ./frontend
	    volumes:
	      - ./frontend:/usr/frontend
	      - /usr/front/node_modules
	    ports:
	      - 8000:8000
	    environment:
	      - PORT=8000
	      - NODE_ENV=development
	  backend:
	    build: .
	    expose:
	      - 8080
	    ports:
	      - 8080:8080
	    depends_on:
	      - frontend
	```

For production:

I've added a conditional check in `build.gradle` (called with `./gradlew build -Pfrontend`):

```gradle
if (project.hasProperty('frontend')) {

    processResources {
        from('frontend/dist/') {
            into 'static'
        }
    }

    processResources.dependsOn('frontend:npm_run_build')
}
```
